export class UsuarioFundacion{
    constructor(
        public _id:string,
        public nombreFundacion:string,
        public representante:string,
        public fechaFundacion:string,
        public correo:string,
        public passwordFundacion:string,
        public passwordTemp:string,
        public sector:string,
        public barrio:string,
        //public calleP:string,
        //public calleS:string,
        public direccionMap:any,
        public telefono:string,
        public celular:string,
        public logo:string,
        public link:string,
        public titular:string,
        public banco:string,
        public numCuenta:string,
        public cedulaCuenta:string,
        public tipoCuenta:string,
        public correoCuenta:string,
        public perfil:string,
        public mision:string,
        public vision:string,
        public estado:number,
        public creadoEn:any
    ){}
}